version: '1.0'
services:
  telegram-server:
    image: dexagon/tg-server:1.0
    ports: 
      - 8081:8081
    environment:
      api_hash: ${API_HASH}
      api_id: ${API_ID}
  
  bot:
    image: botdev:1.0
    volumes:
      - ./dist/index.js:/app/index.js
    env_file:
      - ./.env
    depends_on:
      - telegram-server
      