FROM node:19

COPY dist/index.js /app/
COPY package.json /app/
COPY command-text-blocks.json /app/

WORKDIR /app/

RUN apt-get update && apt-get install -y ffmpeg
RUN npm i

CMD ["npm", "run", "docker-dev"]
